FROM mlabfactory/php8-apache:v1.2

###########################################
# xDebug
###########################################

ARG XDEBUG_MODE=develop,debug

RUN pecl install xdebug \
    && docker-php-ext-enable xdebug
COPY bin/xdebug.ini /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

###########################################